# -*- coding: utf-8 -*-
"""Netchamados.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrxsY3oe8ZHSWNq4dKlLtu_U2hx_tAog
"""

import random
defeito_e_cliente = []

print("======================== Bem Vindos ao Suporte da Netsuporte ===================\n")
print("\t\t\tSuporte Técnico e Desenvolvimento\n")
print("\tAtuando na resolução de problemas técnicos de software e hardware\n")
print("\t=================================================================\n")

print("\tNo intuito de agilizarmos o atendimento aos clientes com problemas técnicos, criamos esse portal para criação e analise de seu chamado.\n")
print("\tPara começarmos preciso que diga em poucas paalavras o que houve com o seu equipamento:\n")
writeclient = input()
print("\tVocê já possui cadastro aqui conosco ?\n")
cadastro_writeclient = input().strip().lower()
defeito_e_cliente.append(writeclient)


if cadastro_writeclient == "sim" :
    print("\tOK, preciso que me passe o numero de serie do equipamento e modelo do equipamento, pode digitar :\n")
    o_numero_do_equipamento = str(input())
    defeito_e_cliente.append(o_numero_do_equipamento)
    print("\tOK Preciso agora apenas da confirmação do seu CNPJ\n")
    cnpj = int(input())
    defeito_e_cliente.append(cnpj)
    print("\tEstamos trabalhando para resolver o seu problema, o seu chamado já foi aberto e em breve o técnico entrará em contato para concerto\n")
    numero_do_chamado = random.randint(100,9999)
    print(f"\tO número do chamado : {numero_do_chamado}\n")
    print("\tAgradecemos a preferencia\n")

elif cadastro_writeclient == "não":
    print("\tPreciso então que me forneça alguns dados para darmos continuidade com o cadastro, pode ser ?\n")
    resp_client = input().strip().lower()

    if resp_client == "sim":
      print("\tOK, preciso que me passe o numero de serie do equipamento juntamente com o modelo e com o numero de algum documento com foto para cadastrarmos o equipamento no seu nome, ou no nome de algum CNPJ no nosso sistema de dados, pode digitar :\n")
      resposta = input().strip().lower()
      defeito_e_cliente.append(resposta)
      print("\tOK, Agora que já possuimos o dados necessários, estou gerando o chamado\n")
      numero_do_chamado = random.randint(100,9999)
      print(f"\tO número do chamado : {numero_do_chamado}\n")

    else :
      print("\tEntendido, mas precisamos realmente das informações pessoais e do equipamento para cadastrarmos no sistema, caso preferir. Deixo meu e-mail, lá te passo mais informações de como manipulamos os dados (edu00coding@netusporte.com)\n")
      print("\tAgradecemos pela preferencia tenha uma boa semana.\n")

else :
    print("\tA opção que você digitou é invalida, preciso que digite se possui ou não cadastro conosco")



